// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQ7yvVG_jdzNgdIpEHhLrStIPeMdCCj4',
    appId: '1:1025107317305:web:7824350d74efcb720333e8',
    messagingSenderId: '1025107317305',
    projectId: 'hugy-e8e0a',
    authDomain: 'hugy-e8e0a.firebaseapp.com',
    storageBucket: 'hugy-e8e0a.appspot.com',
    measurementId: 'G-S3ZKXRG338',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqRXKEAHVo2mMmUPTUGdVdudjuBj1l0eQ',
    appId: '1:1025107317305:android:6c006cffa537dba80333e8',
    messagingSenderId: '1025107317305',
    projectId: 'hugy-e8e0a',
    storageBucket: 'hugy-e8e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPcXheCw9vI-CAcrda1soaLRdljVh3iCU',
    appId: '1:1025107317305:ios:fb2cbcb0d2e054bf0333e8',
    messagingSenderId: '1025107317305',
    projectId: 'hugy-e8e0a',
    storageBucket: 'hugy-e8e0a.appspot.com',
    iosBundleId: 'com.example.hugy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPcXheCw9vI-CAcrda1soaLRdljVh3iCU',
    appId: '1:1025107317305:ios:4183969ed878b8670333e8',
    messagingSenderId: '1025107317305',
    projectId: 'hugy-e8e0a',
    storageBucket: 'hugy-e8e0a.appspot.com',
    iosBundleId: 'com.example.hugy.RunnerTests',
  );
}
